//// This file was auto-generated by ML.NET Model Builder. 
//using Microsoft.AspNetCore.Builder;
//using Microsoft.Extensions.DependencyInjection;
//using Microsoft.Extensions.ML;
//using Microsoft.OpenApi.Models;
//using Microsoft.ML.Data;
//using System.Drawing;
//using System.IO;
//using System.Threading.Tasks;

//// Configure app
//var builder = WebApplication.CreateBuilder(args);
//builder.Services.AddPredictionEnginePool<ImageeMLModel.ModelInput, ImageeMLModel.ModelOutput>()
//    .FromFile("ImageeMLModel.mlnet");

//builder.Services.AddEndpointsApiExplorer();

//builder.Services.AddSwaggerGen(c =>
//{
//    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
//});
//var app = builder.Build();

//app.UseSwagger();

//if (app.Environment.IsDevelopment())
//{
//    app.UseSwagger();
//    app.UseSwaggerUI(c =>
//    {
//        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
//    });
//}


//// Define prediction route & handler
//app.MapPost("/predict",
//    async (PredictionEnginePool<ImageeMLModel.ModelInput, ImageeMLModel.ModelOutput> predictionEnginePool, string imagePath) =>
//    {
//        var input = new ImageeMLModel.ModelInput()
//        {
//            ImageSource = File.ReadAllBytes(imagePath),
//        };

//        return await Task.FromResult(predictionEnginePool.Predict(input));
//    });

//// Run app
//app.Run();

// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<ImageeMLModel.ModelInput, ImageeMLModel.ModelOutput>()
    .FromFile("ImageeMLModel.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}

// Define prediction route & handler for file upload
app.MapPost("/predict", async (
    PredictionEnginePool<ImageeMLModel.ModelInput, ImageeMLModel.ModelOutput> predictionEnginePool,
    IFormFile imageFile) =>
{
    if (imageFile == null || imageFile.Length == 0)
    {
        return Results.BadRequest("No file uploaded.");
    }

    using var ms = new MemoryStream();
    await imageFile.CopyToAsync(ms);
    var input = new ImageeMLModel.ModelInput()
    {
        ImageSource = ms.ToArray(),
    };

    var prediction = predictionEnginePool.Predict(input);
    return Results.Ok(prediction);
});

// Run app
app.Run();